### ISSUE TITLE
Filament color is not showing

### ISSUE THREAD

**Issue by arifroni** [WolfwithSword/Bambu-HomeAssistant-Flows#23]
Since few days (not sure exactly after which update) my filament color in the gui is not showing.

![Image](https://github.com/user-attachments/assets/932a0dd0-869f-4af2-b752-9bc64fb57293)

the color is there

![Image](https://github.com/user-attachments/assets/fac35565-dfac-4320-b374-b982e3b45def)

```
type: custom:tabbed-card
options:
  defaultTabIndex: >
    {% if state_attr('sensor.bambup1s_externalspool_external_spool', 'active')
    %}
      1
    {%else%}
      0
    {%endif%}
tabs:
  - card:
      type: picture-elements
      elements:
        - type: custom:config-template-card
          entities:
            - sensor.bambup1s_ams_tray_1
          element:
            type: state-icon
            entity: sensor.bambup1s_ams_tray_1
            icon: >-
              ${states['sensor.bambup1s_ams_tray_1'].state.toLowerCase() !=
              'empty' ? 'fapro:filament-1' : 'mdi:tray' }
            tap_action: none
            hold_action:
              action: more-info
          style:
            top: 28%
            left: 21.4%
            "--paper-item-icon-color": var(--tray_1_color)
            background-color: rgba(0,0,0,0.5)
            box-shadow: 0 0 5px 5px var(--tray_1_bg)
            border-radius: 50px
            "--mdc-icon-size": 2.4em
        - type: state-label
          entity: sensor.bambup1s_ams_tray_1
          attribute: type
          tap_action:
            action: none
          style:
            top: 77%
            left: 21%
            text-align: center
            font-size: 1em
            background-color: rgba(0,0,0,0.4)
            box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.4)
            border-radius: 50px
            pointer-events: none
            color: "#FFFFFF"
        - type: custom:config-template-card
          entities:
            - sensor.bambup1s_ams_tray_2
          element:
            type: state-icon
            entity: sensor.bambup1s_ams_tray_2
            icon: >-
              ${states['sensor.bambup1s_ams_tray_2'].state.toLowerCase() !=
              'empty' ? 'fapro:filament-1' : 'mdi:tray' }
            tap_action: none
            hold_action:
              action: more-info
          style:
            top: 28%
            left: 39.7%
            "--paper-item-icon-color": var(--tray_2_color)
            background-color: rgba(0,0,0,0.5)
            box-shadow: 0 0 5px 5px var(--tray_2_bg)
            border-radius: 50px
            "--mdc-icon-size": 2.4em
        - type: state-label
          entity: sensor.bambup1s_ams_tray_2
          attribute: type
          tap_action:
            action: none
          style:
            top: 77%
            left: 40%
            text-align: center
            font-size: 1em
            background-color: rgba(0,0,0,0.4)
            box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.4)
            border-radius: 50px
            pointer-events: none
            color: "#FFFFFF"
        - type: custom:config-template-card
          entities:
            - sensor.bambup1s_ams_tray_3
          element:
            type: state-icon
            entity: sensor.bambup1s_ams_tray_3
            icon: >-
              ${states['sensor.bambup1s_ams_tray_3'].state.toLowerCase() !=
              'empty' ? 'fapro:filament-1' : 'mdi:tray' }
            tap_action: none
            hold_action:
              action: more-info
          style:
            top: 28%
            left: 59.7%
            "--paper-item-icon-color": var(--tray_3_color)
            background-color: rgba(0,0,0,0.5)
            box-shadow: 0 0 5px 5px var(--tray_3_bg)
            border-radius: 50px
            "--mdc-icon-size": 2.4em
        - type: state-label
          entity: sensor.bambup1s_ams_tray_3
          attribute: type
          tap_action:
            action: none
          style:
            top: 77%
            left: 60%
            text-align: center
            font-size: 1em
            background-color: rgba(0,0,0,0.4)
            box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.4)
            border-radius: 50px
            pointer-events: none
            color: "#FFFFFF"
        - type: custom:config-template-card
          entities:
            - sensor.bambup1s_ams_tray_4
          element:
            type: state-icon
            entity: sensor.bambup1s_ams_tray_4
            icon: >-
              ${states['sensor.bambup1s_ams_tray_4'].state.toLowerCase() !=
              'empty' ? 'fapro:filament-1' : 'mdi:tray' }
            tap_action: none
            hold_action:
              action: more-info
          style:
            top: 28%
            left: 79.6%
            "--paper-item-icon-color": var(--tray_4_color)
            background-color: rgba(0,0,0,0.5)
            box-shadow: 0 0 5px 5px var(--tray_4_bg)
            border-radius: 50px
            "--mdc-icon-size": 2.4em
        - type: state-label
          entity: sensor.bambup1s_ams_tray_4
          attribute: type
          tap_action:
            action: none
          style:
            top: 77%
            left: 79.6%
            text-align: center
            font-size: 1em
            background-color: rgba(0,0,0,0.4)
            box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.4)
            border-radius: 50px
            pointer-events: none
            color: "#FFFFFF"
        - type: conditional
          conditions:
            - entity: sensor.bambup1s_print_status
              state_not: offline
          elements:
            - type: custom:config-template-card
              entities:
                - sensor.bambup1s_ams_humidity_index
              element:
                type: state-icon
                entity: sensor.bambup1s_ams_humidity_index
                icon: >-
                  ${'fapro:humidity-level-dark-' +
                  states['sensor.bambup1s_ams_humidity_index'].state +
                  '#fullcolor'}
                tap_action: none
                hold_action:
                  action: more-info
              style:
                top: 38.5%
                left: 92.5%
                background-color: "#1c1c1c"
                border-radius: 50px
                border: 0.12em solid var(--humidity-border-color)
                "--mdc-icon-size": 2.05em
      image: /local/media/bambuprinter/AMS_2.png
      card_mod:
        style: |
          ha-card {
            background: none !important;
            border: none !important;
            box-shadow: none !important;
            --humidity-border-color: {% if states('sensor.bambup1s_ams_humidity_index')  != 'unavailable' and states('sensor.bambup1s_ams_humidity_index') | int > 3 %} rgba(255, 255, 126, 0.5); {% elif states('sensor.bambup1s_ams_humidity_index')  != 'unavailable' and states('sensor.bambup1s_ams_humidity_index') | int > 1 %} rgba(228,127,97,1.0); {% else %} rgba(194,74,72,1.0); {% endif %}
            --tray_1_color: {% if is_state_attr('sensor.bambup1s_ams_tray_1', 'color', '#00000000') %} rgb(255, 255, 255); {% else %} {{state_attr('sensor.bambup1s_ams_tray_1', 'color') }}; {% endif %}
            --tray_2_color: {% if is_state_attr('sensor.bambup1s_ams_tray_2', 'color', '#00000000') %} rgb(255, 255, 255); {% else %} {{state_attr('sensor.bambup1s_ams_tray_2', 'color') }}; {% endif %}
            --tray_3_color: {% if is_state_attr('sensor.bambup1s_ams_tray_3', 'color', '#00000000') %} rgb(255, 255, 255); {% else %} {{state_attr('sensor.bambup1s_ams_tray_3', 'color') }}; {% endif %}
            --tray_4_color: {% if is_state_attr('sensor.bambup1s_ams_tray_4', 'color', '#00000000') %} rgb(255, 255, 255); {% else %} {{state_attr('sensor.bambup1s_ams_tray_4', 'color') }}; {% endif %}
            --tray_1_bg: {% if is_state_attr('sensor.bambup1s_ams_tray_1', 'active', true) %} rgba(255, 255, 126, 0.5); {% else %} rgba(0,0,0,0.5); {% endif %}
            --tray_2_bg: {% if is_state_attr('sensor.bambup1s_ams_tray_2', 'active', true) %} rgba(255, 255, 126, 0.5); {% else %} rgba(0,0,0,0.5); {% endif %}
            --tray_3_bg: {% if is_state_attr('sensor.bambup1s_ams_tray_3', 'active', true) %} rgba(255, 255, 126, 0.5); {% else %} rgba(0,0,0,0.5); {% endif %}
            --tray_4_bg: {% if is_state_attr('sensor.bambup1s_ams_tray_4', 'active', true) %} rgba(255, 255, 126, 0.5); {% else %} rgba(0,0,0,0.5); {% endif %}
          }
    attributes:
      label: AMS
  - card:
      type: picture-elements
      elements:
        - type: custom:config-template-card
          entities:
            - sensor.bambup1s_externalspool_external_spool
          element:
            type: state-icon
            entity: sensor.bambup1s_externalspool_external_spool
            icon: >-
              ${states['sensor.bambup1s_externalspool_external_spool'].state.toLowerCase()
              != 'empty' ? 'fapro:filament-1' : 'mdi:tray' }
          style:
            top: 50%
            left: 50%
            transform: translate(-50%, -50%) scale(200%)
            "--paper-item-icon-color": var(--tray_vt_color)
            background-color: rgba(0,0,0,0.5)
            box-shadow: 0 0 5px 5px var(--tray_vt_bg)
            border-radius: 50px
            "--mdc-icon-size": 1.8em
        - type: state-label
          entity: sensor.bambup1s_externalspool_external_spool
          attribute: type
          tap_action:
            action: none
          style:
            top: 50%
            left: 85%
            text-align: center
            font-size: 1em
            background-color: rgba(0,0,0,0.4)
            box-shadow: 0 0 5px 5px rgba(0, 0, 0, 0.4)
            border-radius: 50px
            pointer-events: none
            color: "#FFFFFF"
      image: /local/media/bambuprinter/spool.png
      card_mod:
        style: |
          ha-card {
            margin-left: auto;
            margin-right: auto;
            width: 60%;
            height: 60%;
            background: none !important;
            border: none !important;
            box-shadow: none !important;
            --tray_vt_color: {{state_attr('sensor.bambup1s_externalspool_external_spool', 'color') }};
            --tray_vt_bg: {% if is_state_attr('sensor.bambup1s_externalspool_external_spool', 'active', true) %} rgba(255, 255, 126, 0.5); {% else %} rgba(0,0,0,0.5); {% endif %}
          }
    attributes:
      label: External
```
