### ISSUE TITLE
[Idea] Button card if any update to the cards is available

### ISSUE THREAD

**Issue by informagico** [WolfwithSword/Bambu-HomeAssistant-Flows#8]
This is just an idea/proof of concept and didn't wanted to add a PR 😄 
It would be interesting to have something on the dashboard that let you know if there are any updates available for the cards.

I imagined something like this.

Add a sensor that fetches latest release from GitHub (I know, there are also blueprints/etc..)
```yaml
command_line:
  - sensor:
      command: "curl https://api.github.com/repos/WolfwithSword/Bambu-HomeAssistant-Flows/releases/latest"
      name: wws_ha_bambulab_cards_version
      scan_interval: 3600
      value_template: "{{ value_json.tag_name }}"
```

Add a conditional card on the dashboard that shows a button if any update is available
```yaml
type: conditional
conditions:
  - condition: value
    entity: sensor.wws_ha_bambulab_cards_version
    state_not: unavailable
  - condition: value
    entity: sensor.wws_ha_bambulab_cards_version
    state_not: undefined
  - condition: value
    entity: sensor.wws_ha_bambulab_cards_version
    state_not: {CURRENT_VERSION}
card:
  type: custom:button-card
  name: WolfwithSword's Cards Update Available
  show_icon: true
  icon: mdi:download
  tap_action:
    action: url
    url_path: https://www.wolfwithsword.com/bambulab-home-assistant-dashboard/
  layout: icon_name
  styles:
    grid:
      - grid-template-columns: 20% 1fr
    icon:
      - color: '#f79300'
    name:
      - text-wrap: balance
      - font-weight: bold
```

Example of update available:
![image](https://github.com/WolfwithSword/Bambu-HomeAssistant-Flows/assets/38808827/a4eb3aa7-b7dc-484a-b196-b1a2e521de4e)

Once clicked it redirects to your website.
